// const ios=require('./scripts/run/ios')
const setEnv = require('./scripts/env/setEnv')
const utils = require('./scripts/utils')
const envCommon = require('./scripts/env/common')
const win = require('./scripts/env/win')
const logger = require('./scripts/logger')
const setJavaHome = require('./scripts/env/mac/setJavaHome')
const setCocopod = require('./scripts/env/mac/setCocopod')
const child_process = require('child_process')
const fs = require('fs')
const open = require('open')

// envCommon.checkJAVAHOME({sys:'win32'})
// utils.exec('setx JAVA_HOME DSDSDS')

